### ISSUE TITLE
The dependency on xbmc.python version 2.19.0 could not be satisfied

### ISSUE THREAD

**Issue by s-h-a-d-o-w-pixel** [void-spark/kodi2mqtt#1]
Can't install on kodi 19.1

**Comment by quintz** [comment]
same for me...

**Comment by void-spark** [comment]
Oops, seems I don't get notifications for new issues, you'd think that'd the default on github :)

That said, if you get that error you must not be using the latest code from this repo.
Make sure you use the release from this repo, and delete any old versions you might have.
