### ISSUE TITLE
The master.zip cannot be installed under Matrix 19.3

### ISSUE THREAD

**Issue by Menne01** [void-spark/kodi2mqtt#2]
Hello, 
as written in the header, the install does not work. It would be a wrong structure comes up as an error message.
Regards

**Comment by void-spark** [comment]
I've only ever installed by directly extracting the folder to the Addons folder (so you get Addons/service.mqtt).
Can you indicate exactly how you install the addon? :)
Did it work for you on older versions of Kodi?
Which platform are you using Kodi on? :)

If I look at: https://kodi.wiki/view/Add-on_structure, it seems that the content of the service.mqtt folder should be in the root of the zip to make a 'addon' zip. What you download is just a zip of the source code on github, it's not made to be install-able :)

I'v added a zip to the release that might work (I only re-zipped the sub folder into it), see if that works: https://github.com/void-spark/kodi2mqtt/releases/download/v0.21/service.mqtt.zip :)

**Comment by Menne01** [comment]
Hi, 
nice that you take care of the matter. I tried everything as you wrote. Unfortunately still unsuccessful. See the pictures below. As a platform I use a Fire TV Cube with Kodi Matrix 19.3 .
Manually pasting the unzipped *.zip into the addon folder does not work either, as it is not recognized by Kodi.
Unfortunately, the surfaces of the pictures are in German. 
![grafik](https://user-images.githubusercontent.com/89869516/149986632-fea85834-3277-45af-9d75-0b703e0de0ed.png)
![grafik](https://user-images.githubusercontent.com/89869516/149986745-d0107f58-b5e6-4f0a-beb6-d9fa8b6742b7.png)
![grafik](https://user-images.githubusercontent.com/89869516/149986830-9aa31050-5fea-46d9-b61d-946479226d7b.png)
![grafik](https://user-images.githubusercontent.com/89869516/149987002-a4974f6c-7937-4882-a5ce-64a4bf79610d.png)
![grafik](https://user-images.githubusercontent.com/89869516/149987064-a035eaa7-aae6-4223-a458-ae2f9109b680.png)

Regards

Dirk

**Comment by void-spark** [comment]
Ok, looks like the plugin/folder/zip name was not according to the spec.
Try thisone: https://github.com/void-spark/kodi2mqtt/releases/download/v0.21/plugin.service.mqtt.zip :)
I tested it on my box which is also19.3, and it works here :)

**Comment by Menne01** [comment]
Great, the installing has now worked and I also have brokerstates, but the operation via playbackstate doesn't work.
![grafik](https://user-images.githubusercontent.com/89869516/150835948-ea3b2d08-78aa-4836-a958-73c778371cc3.png)
In the field I can type what I want, no reaction to the player.
I always read from command/playbackstate. But that doesn't exist. Status/playbackstate only

**Comment by void-spark** [comment]
Right, think there were some minor incompatibilities with new python/xbmc/libs :)
Try the new one: https://github.com/void-spark/kodi2mqtt/releases/download/v0.22/plugin.service.mqtt.zip
Note: After uninstalling old version I had to restart kodi, or else I got wrong structure error again while installing the new zip.
Think that might be a odd Kodi issue :)

**Comment by Menne01** [comment]
Unfortunately no change yet. The generated data points can be seen in the images. New additions are MQTT below, but what for? That's already a point for connected. So unnecessary. The data point for entering /kodi/command/playbackstate...is missing. Also there are missing entries in kodi/status/progress and kodi/status/title, the fields are (null).
![grafik](https://user-images.githubusercontent.com/89869516/150884677-3687f9a6-7369-413b-8bd5-d286b820c2a6.png)
![grafik](https://user-images.githubusercontent.com/89869516/150884795-62254e2a-4368-44b3-afb9-131094ff1f51.png)

**Comment by void-spark** [comment]
I don't know which program you're using to send/receive mqtt messages, but mqtt doesn't notify anyone of topics it's listening to :)
You should just be able to send values to 'kodi/command/playbackstate' :)
Progress and title should be available when something is playing:
![image](https://user-images.githubusercontent.com/81029971/150927441-067be01c-6f6e-4bca-9c28-7b14103e330c.png)

**Comment by void-spark** [comment]
Keep in mind there's been different improvements by different people for different usages, MQTT is a very free protocol, and not everyone uses it with the same programs :) I just connect it to node red for example :)

**Comment by void-spark** [comment]
Did it work in the end? If I hear nothing I'll close the issue :)
